name: build-and-publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'LWJGLX' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Build with Maven
      run: ./mvnw -B package -DskipTests
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase:  ${{ secrets.gpg_passphrase }}
        nexus_username:  ${{ secrets.nexus_username }}
        nexus_password:  ${{ secrets.nexus_password }}
        maven_args: -Durlcheck.disabled=true -Dmaven.test.skip=true
